enable: False
use_rm: False
use_valid: False
val_batch_size: ${data.val_batch_size}
strategy: fsdp
ckpt_path: ~/Unbabel/wmt22-comet-da/checkpoints/model.ckpt
tokenizer_path: ${actor_rollout_ref.model.path}
trust_remote_code: False
# model_path: ~/Unbabel/XCOMET-XL/checkpoints/model.ckpt
  # comet: ~/Unbabel/wmt22-comet-da/checkpoints/model.ckpt
forward_micro_batch_size_per_gpu: 8
ulysses_sequence_parallel_size: 1 # sp size
use_dynamic_bsz: False